I've found that the issue is I was using chef 12.0.3, and in line 109 of /usr/local/rvm/gems/ruby-2.0.0-p598/gems/chef-12.0.3/lib/chef/dsl/recipe.rb
     resource.load_prior_resource(type, name)

But in chef-metal-ssh-0.1.2/lib/chef/resource/ssh_cluster.rb:18

it's defined as
def load_prior_resource
Chef::Log.debug("Overloading #{resource_name}.load_prior_resource with
NOOP")
end
so it throws

ArgumentError: wrong number of arguments (2 for 0)